[build]
  # Build command (leave empty if no build process)
  command = ""
  # Directory to publish (adjust based on project structure)
  publish = "."

[build.environment]
  # Node.js version if needed
  NODE_VERSION = "18"

# SPA routing configuration
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Optional: Custom headers for better caching
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin" 